on: [push, pull_request]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install Lua
      run: sudo apt-get install lua5.3

    - name: Run Lua tests
      run: |
        lua5.3 -e 'local variable1 = "Hola2"; assert(variable1 == "Hola", "Variable1 no se inicializó correctamente")'
        lua5.3 -e 'local variable2 = 42; assert(variable2 == 42, "Variable2 no se inicializó correctamente")'
